Repository nginx/ansible-role-nginx-config, pull requests merged in 2020-09, with the labels that each got.

#16 Update Ansible to 2.9.12 and explicitly set mode on relevant tasks
  .ansible-lint
  .travis.yml
  CHANGELOG.md
  molecule/common/playbooks/default_verify.yml
  molecule/common/playbooks/module_verify.yml
  molecule/common/playbooks/stable_push_verify.yml
  molecule/common/requirements.yml
  molecule/default/molecule.yml
  molecule/default_alpine/molecule.yml
  molecule/default_centos/molecule.yml
  molecule/module/molecule.yml
  molecule/module_alpine/molecule.yml
  molecule/module_centos/molecule.yml
  molecule/stable_push/molecule.yml
  molecule/stable_push_alpine/molecule.yml
  molecule/stable_push_centos/molecule.yml
  tasks/conf/template-config.yml
  tasks/conf/upload-config.yml
Labels: improvement

#17 Update Ansible to 2.9.13
  .travis.yml
Labels: improvement

#18 Update Ansible Galaxy metadata
  meta/main.yml
Labels: improvement

#19 Fix configs cleanup
  CHANGELOG.md
  defaults/main/main.yml
  tasks/conf/cleanup-config.yml
Labels: bug

#22 Refactor modules
  CHANGELOG.md
  README.md
  defaults/main/main.yml
  defaults/main/template.yml
  molecule/common/playbooks/default_converge.yml
  molecule/common/playbooks/module_converge.yml
  molecule/common/playbooks/prepare.yml
  tasks/conf/template-config.yml
  tasks/main.yml
  templates/nginx.conf.j2
Labels: breaking change, enhancement

#23 Add support for Alpine 3.12
  .travis.yml
  CHANGELOG.md
  README.md
  molecule/cleanup_module/molecule.yml
  molecule/cleanup_module_alpine/molecule.yml
  molecule/cleanup_module_centos/molecule.yml
  molecule/common/playbooks/cleanup_module_converge.yml
  molecule/common/playbooks/cleanup_module_verify.yml
  molecule/common/playbooks/default_converge.yml
  molecule/default_alpine/molecule.yml
  molecule/stable_push_alpine/molecule.yml
Labels: feature

#24 Update README, set yamllint version, add rewrite to tests
  .travis.yml
  README.md
  molecule/common/playbooks/default_converge.yml
Labels: enhancement, feature

#25 Update docs to fix master references
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  defaults/main/main.yml
  handlers/main.yml
  molecule/common/Dockerfile.j2
  tasks/conf/debug-output.yml
  tasks/conf/upload-config.yml
  tasks/config/cleanup-config.yml
  tasks/config/debug-output.yml
  tasks/config/template-config.yml
  tasks/config/upload-config.yml
  tasks/main.yml
  tasks/prerequisites/setup-selinux.yml
Labels: documentation, enhancement, feature

#26 Add support for NGINX App Protect directives
  .travis.yml
  CHANGELOG.md
  README.md
  defaults/main/template.yml
  defaults/main/upload.yml
  files/config/http/.gitkeep
  files/config/stream/.gitkeep
  handlers/main.yml
  molecule/cleanup_module/converge.yml
  molecule/cleanup_module/molecule.yml
  molecule/cleanup_module/verify.yml
  molecule/cleanup_module_alpine/molecule.yml
  molecule/cleanup_module_centos/molecule.yml
  molecule/common/Dockerfile.j2
  molecule/common/files/license/.gitkeep
  molecule/common/playbooks/oss_prepare.yml
  molecule/common/playbooks/oss_requirements.yml
  molecule/common/playbooks/plus_prepare.yml
  molecule/common/playbooks/plus_requirements.yml
  molecule/common/playbooks/prepare.yml
  molecule/default/converge.yml
  molecule/default/molecule.yml
  molecule/default/verify.yml
  molecule/default_alpine/molecule.yml
  molecule/default_centos/molecule.yml
  molecule/plus/converge.yml
  molecule/plus/molecule.yml
  molecule/plus/verify.yml
  molecule/stable_push/converge.yml
  molecule/stable_push/molecule.yml
  molecule/stable_push/verify.yml
  molecule/stable_push_alpine/molecule.yml
  tasks/config/cleanup-config.yml
  tasks/config/debug-output.yml
  tasks/config/template-config.yml
  tasks/config/upload-config.yml
  tasks/main.yml
  tasks/prerequisites/setup-selinux.yml
  templates/http/app_protect.j2
  templates/http/default.conf.j2
  templates/nginx.conf.j2
Labels: enhancement, feature

#29 Fixes #28: Use port 8080 by default for status page
  .travis.yml
  CHANGELOG.md
  defaults/main/template.yml
  templates/http/status.conf.j2
Labels: breaking change, bug

#31 Add survey to README
  CHANGELOG.md
  README.md
Labels: enhancement
