Repository nginx/ansible-role-nginx-config, pull requests merged in 2021-02, with the labels that each got.

#70 Update GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: enhancement

#71 Update GitHub workflows
  .github/workflows/galaxy.yml
  .github/workflows/molecule.yml
Labels: enhancement

#72 Fix `package` module in Molecule verification tests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
  .github/SECURITY.md
  CHANGELOG.md
  molecule/cleanup_module/verify.yml
  molecule/default/verify.yml
  molecule/plus/verify.yml
  molecule/stable_push/verify.yml
  templates/http/default.conf.j2
Labels: enhancement

#73 Remove `web_server` and `reverse_proxy` template dictionary keys
  CHANGELOG.md
  molecule/default/converge.yml
  molecule/plus/converge.yml
  templates/http/default.conf.j2
Labels: breaking change

#76 Replace nested dictionaries with lists
  CHANGELOG.md
  defaults/main/template.yml
  molecule/default/converge.yml
  molecule/plus/converge.yml
  tasks/config/template-config.yml
  templates/http/default.conf.j2
  templates/stream/default.conf.j2
  templates/www/index.html.j2
Labels: breaking change, enhancement

#77 Remove redundant forward slashes
  tasks/config/template-config.yml
Labels: enhancement

#79 Refactor NGINX config uploads
  .gitignore
  CHANGELOG.md
  defaults/main/upload.yml
  molecule/common/files/http/default.conf
  molecule/common/files/http/server_one.conf
  molecule/common/files/http/server_two.conf
  molecule/common/files/nginx.conf
  molecule/common/files/ssl/molecule.crt
  molecule/common/files/ssl/molecule.key
  molecule/common/files/www/index.html
  molecule/stable_push/converge.yml
  tasks/config/upload-config.yml
  tasks/main.yml
Labels: breaking change, enhancement

#67 Rename html_file_name to index and add index to server_block
  CHANGELOG.md
  defaults/main/template.yml
  molecule/default/converge.yml
  molecule/plus/converge.yml
  templates/http/default.conf.j2
Labels: enhancement

#81 Change directory to `/etc/nginx` before running NGINX config check
  CHANGELOG.md
  handlers/main.yml
Labels: bug

#85 Refactor HTTP Upstream module
  CHANGELOG.md
  defaults/main/template.yml
  molecule/default/converge.yml
  molecule/plus/converge.yml
  templates/http/default.conf.j2
  templates/http/upstream.j2
Labels: breaking change
