Repository nginx/ansible-role-nginx-config, pull requests merged in 2021-01, with the labels that each got.

#55 Update Python packages and update copyright notice
  .github/workflows/molecule.yml
  CHANGELOG.md
  README.md
Labels: enhancement

#56 Add support for NGINX GRPC directives
  .github/workflows/galaxy.yml
  CHANGELOG.md
  README.md
  defaults/main/template.yml
  meta/main.yml
  molecule/common/playbooks/oss_requirements.yml
  molecule/common/playbooks/plus_requirements.yml
  molecule/default/converge.yml
  templates/http/default.conf.j2
  templates/http/grpc.j2
  templates/nginx.conf.j2
Labels: enhancement

#57 Fix #50: Add upstream server backup parameter to templates
  CHANGELOG.md
  molecule/default/converge.yml
  molecule/plus/converge.yml
  templates/http/default.conf.j2
  templates/stream/default.conf.j2
Labels: enhancement

#58 Add support for NGINX GZIP directives
  CHANGELOG.md
  defaults/main/template.yml
  molecule/default/converge.yml
  templates/http/default.conf.j2
  templates/http/gzip.j2
  templates/nginx.conf.j2
Labels: enhancement

#59 Add support for configuration snippets
  CHANGELOG.md
  defaults/main/upload.yml
  files/config/snippets/.gitkeep
  molecule/common/files/snippets/location_snippet.conf
  molecule/stable_push/converge.yml
  tasks/config/upload-config.yml
Labels: feature

#60 Add support for Dependabot
  .github/dependabot.yml
  .github/workflows/galaxy.yml
  .github/workflows/molecule.yml
  .github/workflows/requirements_galaxy.txt
  .github/workflows/requirements_molecule.txt
  CHANGELOG.md
Labels: feature

#65 Make `proxy_pass` optional
  CHANGELOG.md
  templates/http/default.conf.j2
Labels: bug

#63 Tweak inconsistent types
  CHANGELOG.md
  templates/http/default.conf.j2
  templates/nginx.conf.j2
  templates/stream/default.conf.j2
Labels: bug

#66 Add Jinja2 checks to all config template parameters
  CHANGELOG.md
  defaults/main/template.yml
  templates/nginx.conf.j2
Labels: bug

#64 Rename `proxy_hide_headers` to `proxy_hide_header`
  CHANGELOG.md
  defaults/main/template.yml
  molecule/default/converge.yml
  molecule/plus/converge.yml
  templates/http/default.conf.j2
Labels: breaking change
