Repository nginx/ansible-role-nginx-config, pull requests merged in 2021-04, with the labels that each got.

#112 Update Ansible collections
  .github/workflows/molecule.yml
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies, enhancement

#114 Add support for NAP 3.2 security log lists
  CHANGELOG.md
  defaults/main/template.yml
  molecule/common/requirements/oss_requirements.yml
  molecule/common/requirements/plus_requirements.yml
  molecule/plus/converge.yml
  templates/http/app_protect.j2
Labels: feature

#116 Add `server_names_hash_bucket_size` directive
  CHANGELOG.md
  defaults/main/template.yml
  molecule/default/converge.yml
  molecule/plus/converge.yml
  templates/nginx.conf.j2
Labels: enhancement

#117 Implement Release Drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  CHANGELOG.md
Labels: feature

#118 Update Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies, documentation
