Repository nginx/ansible-role-nginx-config, pull requests merged in 2021-03, with the labels that each got.

#87 Refactor HTTP Proxy module
  CHANGELOG.md
  defaults/main/template.yml
  molecule/default/converge.yml
  molecule/plus/converge.yml
  tasks/config/template-config.yml
  templates/http/default.conf.j2
  templates/http/proxy.j2
  templates/nginx.conf.j2
Labels: breaking change

#95 Fix missing GRPC boolean check in GRPC template
  CHANGELOG.md
  templates/http/grpc.j2
Labels: bug

#97 Proxy related variables should only specified under the `http` template
  defaults/main/template.yml
Labels: documentation

#99 Fix `nginx_config_cleanup_paths` not working as intended
  CHANGELOG.md
  molecule/cleanup_module/prepare.yml
  molecule/cleanup_module/verify.yml
  tasks/config/cleanup-config.yml
Labels: bug

#100 feat: make http settings access_log_format and keepalive_timeout optional
  templates/nginx.conf.j2
Labels: enhancement

#103 Update Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: enhancement

#104 Add explicit Jinja2 requirement
  .github/workflows/requirements/requirements_molecule.txt
  CHANGELOG.md
  README.md
Labels: feature

#105 Tweak Molecule tests to account for the current supported platforms
  CHANGELOG.md
  README.md
  meta/main.yml
  molecule/cleanup_module/molecule.yml
  molecule/common/requirements/plus_requirements.yml
  molecule/default/molecule.yml
  molecule/plus/molecule.yml
  molecule/plus/verify.yml
  molecule/stable_push/molecule.yml
Labels: enhancement
