Repository nginx/ansible-role-nginx-config, pull requests merged in 2021-09, with the labels that each got.

#162 Add reconnect_period_seconds for NAP 3.5
  CHANGELOG.md
  defaults/main/template.yml
  templates/http/app_protect_waf.j2
Labels: enhancement

#168 Refactor HTTP core module
  .github/release-drafter.yml
  CHANGELOG.md
  README.md
  defaults/main/template.yml
  molecule/cleanup_module/molecule.yml
  molecule/common/requirements/oss_requirements.yml
  molecule/common/requirements/plus_requirements.yml
  molecule/default/converge.yml
  molecule/default/molecule.yml
  molecule/default/verify.yml
  molecule/plus/converge.yml
  molecule/stable_push/molecule.yml
  tasks/config/template-config.yml
  templates/core.j2
  templates/http/api.conf.j2
  templates/http/app_protect.j2
  templates/http/app_protect_dos.j2
  templates/http/app_protect_waf.j2
  templates/http/auth.j2
  templates/http/core.j2
  templates/http/default.conf.j2
  templates/http/grpc.j2
  templates/http/gzip.j2
  templates/http/modules.j2
  templates/http/proxy.j2
  templates/http/ssl.j2
  templates/http/status.conf.j2
  templates/http/upstream.j2
  templates/nginx.conf.j2
Labels: breaking change

#170 Bump Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies

#171 Update GitHub Actions
  .github/workflows/molecule.yml
  CHANGELOG.md
  molecule/plus/molecule.yml
Labels: enhancement
