Repository nginx/ansible-role-nginx-config, pull requests merged in 2021-06, with the labels that each got.

#135 Make proxy_read_timeout a string instead of a boolean
  templates/http/proxy.j2
Labels: bug

#137 Replace "yes"/"no" boolean values with "true"/"false"
  .github/workflows/galaxy.yml
  .github/workflows/molecule.yml
  .github/workflows/release-drafter.yml
  .yamllint
  CHANGELOG.md
  handlers/main.yml
  molecule/cleanup_module/verify.yml
  molecule/default/verify.yml
  molecule/plus/prepare.yml
  molecule/plus/verify.yml
  molecule/stable_push/verify.yml
  tasks/config/debug-output.yml
  tasks/config/template-config.yml
  tasks/config/upload-config.yml
  tasks/prerequisites/setup-selinux.yml
Labels: enhancement

#138 Bump Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies

#141 Refactor HTTP auth modules
  CHANGELOG.md
  defaults/main/template.yml
  molecule/default/converge.yml
  molecule/plus/converge.yml
  templates/http/auth.j2
  templates/http/default.conf.j2
Labels: breaking change

#143 Bump the role versions used when testing the role
  CHANGELOG.md
  molecule/common/requirements/oss_requirements.yml
  molecule/common/requirements/plus_requirements.yml
Labels: enhancement

#144 Bump Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies, enhancement

#148 Fix default template for nginx.conf
  CHANGELOG.md
  defaults/main/template.yml
  templates/http/app_protect.j2
  templates/nginx.conf.j2
Labels: bug, enhancement

#142 Include alias location statement support
  CHANGELOG.md
  defaults/main/template.yml
  molecule/common/files/http/server_two.conf
  molecule/default/converge.yml
  molecule/default/verify.yml
  templates/http/default.conf.j2
Labels: enhancement
