Repository nginx/ansible-role-nginx-config, pull requests merged in 2022-04, with the labels that each got.

#239 Streamline configuring SELinux
  CHANGELOG.md
  defaults/main/selinux.yml
  tasks/prerequisites/setup-selinux.yml
Labels: enhancement

#240 Implement RealIP module
  CHANGELOG.md
  defaults/main/template.yml
  molecule/default/converge.yml
  molecule/plus/converge.yml
  templates/http/default.conf.j2
  templates/http/modules.j2
Labels: enhancement, feature

#241 Bump `community.docker` collection
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies

#242 Add mirror and gunzip modules
  CHANGELOG.md
  defaults/main/template.yml
  molecule/default/converge.yml
  molecule/plus/converge.yml
  templates/http/default.conf.j2
  templates/http/modules.j2
Labels: enhancement

#243 Bump `community.general` collection
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies

#244 Fix formatting of access allow
  templates/http/default.conf.j2
Labels: enhancement
