Repository nginx/ansible-role-nginx-config, pull requests merged in 2022-03, with the labels that each got.

#229 Ansible check mode fails if NGINX is not installed
  CHANGELOG.md
  handlers/main.yml
Labels: bug

#231 Rename modules to use Ansible FQCNs
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  meta/main.yml
  tasks/prerequisites/setup-selinux.yml
Labels: feature, dependencies

#232 Use labels for loops in template-config to reduce amount of data in output
  CHANGELOG.md
  tasks/config/template-config.yml
Labels: enhancement
