Repository nginx/ansible-role-nginx-config, pull requests merged in 2022-02, with the labels that each got.

#213 HTTP template: Fix bug with single custom_directives
  CHANGELOG.md
  templates/http/default.conf.j2
Labels: bug

#206 Automatically create NGINX client body temp path directory
  CHANGELOG.md
  molecule/default/converge.yml
  molecule/default/verify.yml
  tasks/config/template-config.yml
Labels: feature

#217 Refactor NGINX stream templates
  CHANGELOG.md
  molecule/common/requirements/oss_requirements.yml
  molecule/common/requirements/plus_requirements.yml
  molecule/default/converge.yml
  molecule/plus/converge.yml
  tasks/config/template-config.yml
  templates/stream/core.j2
  templates/stream/default.conf.j2
  templates/stream/modules.j2
  templates/stream/proxy.j2
  templates/stream/ssl.j2
  templates/stream/upstream.j2
Labels: breaking change

#218 Fix typo in REST API template
  CHANGELOG.md
  defaults/main/template.yml
  templates/http/api.conf.j2
Labels: bug

#220 Fix bugged conditional check in the `http/ssl.j2` Jinja2 template
  CHANGELOG.md
  templates/http/ssl.j2
Labels: bug

#222 Change HTML template parameters in line with similar parameters
  CHANGELOG.md
  defaults/main/template.yml
  molecule/default/converge.yml
  molecule/plus/converge.yml
  tasks/config/template-config.yml
Labels: breaking change

#212 Do not set SELinux to permissive when it is enabled in check mode
  CHANGELOG.md
  tasks/prerequisites/setup-selinux.yml
Labels: bug

#225 Bump Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
  molecule/common/requirements/oss_requirements.yml
  molecule/common/requirements/plus_requirements.yml
Labels: dependencies
