Repository nginx/ansible-role-nginx-config, pull requests merged in 2024-07, with the labels that each got.

#445 chore: Remove CentOS 7 artifacts/tests/metadata
  CHANGELOG.md
  defaults/main/selinux.yml
  meta/main.yml
  molecule/common/Dockerfile.j2
  molecule/common/requirements/oss_requirements.yml
  molecule/common/requirements/plus_requirements.yml
  molecule/complete_plus/converge.yml
  molecule/complete_plus/molecule.yml
  molecule/complete_plus/prepare.yml
  molecule/complete_plus/verify.yml
  tasks/prerequisites/setup-selinux.yml
Labels: tests

#446 ci: Update GH Actions to Ubuntu 24.04 and switch from release tags to hashes
  .github/workflows/f5-cla.yml
  .github/workflows/galaxy.yml
  .github/workflows/molecule.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  CHANGELOG.md
Labels: github_actions

#447 chore: Remove platform metadata from the Ansible Galaxy role metadata
  .ansible-lint
  CHANGELOG.md
  README.md
  meta/main.yml
Labels: enhancement

#449 ci: Update F5 CLA action
  .github/workflows/f5-cla.yml
  CHANGELOG.md
Labels: enhancement, github_actions

#448 docs: Update community docs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
  SUPPORT.md
Labels: documentation

#450 feat: Bump Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: enhancement, feature, dependencies

#451 docs: Update README
  .github/workflows/galaxy.yml
  .github/workflows/molecule.yml
  .github/workflows/requirements/requirements_collections.yml
  .github/workflows/requirements/requirements_galaxy.txt
  CHANGELOG.md
  README.md
Labels: documentation, dependencies

#454 ci: Implement OSSF Scorecard
  .github/workflows/ossf-scorecard.yml
  CHANGELOG.md
Labels: enhancement, github_actions

#455 test: Update RHEL UBI images to UBI 9.4
  CHANGELOG.md
  molecule/api_plus/molecule.yml
  molecule/cleanup_config/molecule.yml
  molecule/complete/molecule.yml
  molecule/default/molecule.yml
  molecule/push_config/molecule.yml
  molecule/reverse_proxy/molecule.yml
  molecule/stub_status/molecule.yml
  molecule/web_server/molecule.yml
Labels: tests

#429 Correct runtime error during cleanup.
  CHANGELOG.md
  tasks/config/cleanup-config.yml
Labels: bug

#456 feat: Add Ansible/Jinja2/Collections validation
  CHANGELOG.md
  tasks/validate/validate.yml
  vars/main.yml
Labels: feature
