Repository nginx/ansible-role-nginx-config, pull requests merged in 2025-05, with the labels that each got.

#555 fix: Default NGINX PID path
  CHANGELOG.md
  defaults/main/template.yml
  molecule/common/files/nginx.conf
  molecule/complete/converge.yml
  molecule/complete_plus/converge.yml
  molecule/default/converge.yml
Labels: bug

#554 feat: Ensure NGINX service is enabled on boot when reloading
  handlers/main.yml
Labels: enhancement

#559 fix: NGINX `set_real_ip_from` directive should be a list
  CHANGELOG.md
  molecule/complete_plus/converge.yml
  templates/http/modules.j2
Labels: bug

#558 fix: Properly check Ansible collections in check mode
  CHANGELOG.md
  tasks/validate/validate.yml
Labels: bug

#439 fix: Correct default `http_version` from float to string
  CHANGELOG.md
  defaults/main/template.yml
  molecule/complete/converge.yml
  molecule/complete_plus/converge.yml
Labels: bug, tests

#561 feat: Template support for the NGINX Stream map module
  CHANGELOG.md
  defaults/main/template.yml
  molecule/complete/converge.yml
  molecule/complete_plus/converge.yml
  templates/stream/modules.j2
Labels: enhancement

#560 feat: Template support for the NGINX HTTP gzip static module
  CHANGELOG.md
  defaults/main/template.yml
  molecule/complete/converge.yml
  molecule/complete_plus/converge.yml
  templates/http/modules.j2
  templates/stream/modules.j2
Labels: enhancement

#562 feat: Add support for the NGINX ngx_mgmt_module module.
  .github/workflows/molecule.yml
  CHANGELOG.md
  defaults/main/template.yml
  molecule/entitlement_plus/converge.yml
  molecule/entitlement_plus/molecule.yml
  molecule/entitlement_plus/prepare.yml
  molecule/entitlement_plus/verify.yml
  templates/core.j2
  templates/nginx.conf.j2
Labels: enhancement

#563 docs: Fix survey link
  README.md
Labels: bug, documentation
